fix: add express middle ware to logger.ts. add routers to server.ts
team-KANSAT-P/travel-recs pull request #13
Opened 2024-11-21 22:30 UTC by nanyi-deng

2024-11-21 23:36 UTC, aidanprior requested changes

2024-11-21 23:36 UTC, aidanprior commented on server/controllers/logger.ts
> +    return next(error);
@nanyi-deng error is not defined here, you need to pass an object of type `ServerError` (check kenny's types file)

2024-11-21 23:36 UTC, aidanprior commented on server/controllers/logger.ts
> +      return res.status(500).json({ error: 'Failed to insert data' });
@nanyi-deng We should use the global error handler here too

2024-11-21 23:36 UTC, aidanprior commented on server/controllers/logger.ts
> +    res.locals.insertedData = data[0];
Because we are pulling all the data off `res.locals`, I don't think we need to put the same data back on it.

2024-11-21 23:36 UTC, aidanprior commented on server/controllers/logger.ts
> +export const getUserDataMiddleware = async (
@nanyi-deng I'm not sure that we need this functionality, as we will probably only manually pull data from our database? Not sure.

2024-11-21 23:36 UTC, aidanprior commented on server/server.ts
> +  openaiNLPQuery,
@nanyi-deng I think the reason you are getting linting errors here is because you need to merge with dev

2024-11-21 23:36 UTC, aidanprior commented on server/server.ts
> +  //logger?
@nanyi-deng This is where we should be including that `insertUserDataMiddleware` middleware function, so it has access to the data on `res.locals`

2024-11-21 23:36 UTC, aidanprior commented on server/server.ts
> +app.post('/insert', insertUserDataMiddleware, (req: Request, res: Response) => {
I'm not sure this is neccessary, as the only logging we would be doing is during the `POST /api/recommendations` route handling

2024-11-21 23:36 UTC, aidanprior commented on server/server.ts
> +app.get('/fetch', getUserDataMiddleware, (req: Request, res: Response) => {
Similar to my other comment, I don't think we need this route.

2024-11-22 15:37 UTC, alex-joseph-stewart approved these changes

2024-11-22 15:46 UTC, aidanprior approved these changes

2024-11-22 15:46 UTC, merged